name: Non-Vendored Linux aarch64
on:
  pull_request:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - '**/README.md'
      - '**/.gitignore'
env:
  RUSTFLAGS: -C linker=aarch64-linux-gnu-gcc
  CMAKE_C_COMPILER: aarch64-linux-gnu-gcc
  CMAKE_CXX_COMPILER: aarch64-linux-gnu-g++
  CC: aarch64-linux-gnu-gcc
  CXX: aarch64-linux-gnu-g++
  LD: aarch64-linux-gnu-ld
  CPATH: /usr/local/include
  LIBRARY_PATH: /usr/local/lib
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget build-essential llvm clang libclang-dev gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
      - name: capstone from source
        run: |
          wget https://github.com/aquynh/capstone/archive/4.0.2.tar.gz
          tar xf 4.0.2.tar.gz
          cd capstone-4.0.2
          mkdir build
          cd build
          uname -a
          cmake ..
          make -j 8
          sudo make install
      - name: Install cross-compile tool
#        uses: actions-rs/toolchain@v1
        uses: taiki-e/setup-cross-toolchain-action@v1
        with:
          toolchain: stable
          target: aarch64-unknown-linux-gnu
          override: true
          components: rustfmt
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --target aarch64-unknown-linux-gnu
