name: Non-Vendored macOS aarch64
on:
  pull_request:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - '**/README.md'
      - '**/.gitignore'
      - '**/*.sh'
jobs:
  test:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [arm64]
    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        run: |
          brew install llvm capstone
      - name: Install cross-compile tool
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-apple-darwin
          override: true
          components: rustfmt
      - name: cargo test
        env:
          CPATH: $(brew --prefix)/Cellar/capstone/4.0.2/include
          LIBRARY_PATH: $(brew --prefix)/Cellar/capstone/4.0.2/lib
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --target=aarch64-apple-darwin
