name: Vendored Linux aarch64
on:
  pull_request:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - '**/README.md'
      - '**/.gitignore'
env:
  RUSTFLAGS: -C linker=gcc-11-aarch64-linux-gnu
jobs:
  test:
    name: Test on Linux aarch64
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget build-essential llvm clang libclang-dev gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
      - name: Install cross-compile tool
        uses: actions-rs/toolchain@v1
#        uses: taiki-e/setup-cross-toolchain-action@v1
        with:
          toolchain: stable
          target: aarch64-unknown-linux-gnu
          override: true
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --target aarch64-unknown-linux-gnu --features=vendored
