name: Vendored macOS aarch64
on:
  pull_request:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - '**/README.md'
      - '**/.gitignore'
      - '**/*.sh'
env:
  RUSTFLAGS: -C linker=aarch64-apple-darwin21.1-clang
jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install cross-compile tool
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-apple-darwin
          override: true
          components: rustfmt
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --target=aarch64-apple-darwin --features=vendored
